/// Application module
pub mod app {
    use std::env;
    use std::error;
    use std::fs;
    use std::io;
    use std::path::PathBuf;
    use std::process;
    use std::os::unix::fs::PermissionsExt;

    pub use crate::config;
    pub use crate::utils::system;

    pub const NAME: &str = "binx";
    pub const VERSION: &str = "0.1.0";
    pub const DESCRIPTION: &str = "Execute binaries with alias management";
    pub const APP_HOME: &str = ".binx";

    pub fn mode_version() -> String {
        if cfg!(debug_assertions) {
            let timestamp = system::get_timestamp().to_string();
            format!("{}-{}", VERSION, timestamp)
        } else {
            VERSION.to_string()
        }
    }

    /// Gets the installation directory path (~/.binx)
    pub fn app_home_dir() -> Result<PathBuf, io::Error> {
        let home_dir = system::get_home_dir()?;
        let install_dir = PathBuf::from(home_dir).join(APP_HOME);
        // Create installation directory if it doesn't exist
        if !install_dir.exists() {
            fs::create_dir_all(&install_dir)?;
        }
        Ok(install_dir)
    }

     /// Gets the installation executable path (~/.binx/binx)
    pub fn app_full_path() -> Result<PathBuf, io::Error> {
        let install_dir = app_home_dir()?;
        Ok(install_dir.join(NAME))
    }

    /// Returns the .desktop filename with "binx_" prefix for an alias
    pub fn desktop_filename(alias: &str) -> String {
        format!("binx_{}", alias)
    }

    /// Gets alias data from config
    pub fn get_alias_data<'a>(alias: &str, config: &'a mut config::Config) -> Result<&'a config::ConfigAlias, io::Error> {
        match config.aliases.get(alias) {
            Some(data) => Ok(data),
            None => Err(io::Error::new(io::ErrorKind::NotFound, "Alias not found"))
        }
    }

    /// Removes an alias and all associated files (script, .desktop, icon)
    pub fn remove_alias(alias: &str, config: &mut config::Config) -> Result<(), Box<dyn error::Error>> {
        let alias_data = get_alias_data(alias, config)?;

        // Remove script from ~/.binx/
        if let Some(script_path) = &alias_data.script  {
            if !script_path.is_empty() {
                let p = PathBuf::from(script_path);
                if p.exists() {
                    fs::remove_file(&p)?;
                    println!("Removed script: {:?}", p);
                }
            }
        }

        // Remove .desktop file
        let apps_dir = system::get_user_applications_dir()?;
        let desktop_name = desktop_filename(alias);
        let desktop_file_path = apps_dir.join(format!("{}.desktop", desktop_name));
        if desktop_file_path.exists() {
            fs::remove_file(&desktop_file_path)?;
            println!("Removed .desktop file: {:?}", desktop_file_path);

            // Update desktop database
            match process::Command::new("update-desktop-database")
                .arg(&apps_dir)
                .output()
            {
                Ok(output) if output.status.success() => {
                    println!("Desktop database updated");
                }
                _ => {}
            }
        }

        // Remove icon if installed
        if let Some(icon_path) = &alias_data.icon {
            if !icon_path.is_empty() {
                let home_dir = system::get_home_dir()?;
                let icons_base = PathBuf::from(&home_dir).join(".local/share/icons/hicolor");

                for dir in &["scalable/apps", "256x256/apps"] {
                    for ext in &["svg", "png"] {
                        let icon_path = icons_base.join(dir).join(format!("{}.{}", icon_path, ext));
                        if icon_path.exists() {
                            fs::remove_file(&icon_path)?;
                            println!("Removed icon: {:?}", icon_path);
                        }
                    }
                }
            }
        }

        // Remove from config
        config.aliases.remove(alias);

        println!("Removed alias '{}'", alias);

        Ok(())
    }

    /// Installs a script for the target in ~/.binx/ with executable permissions
    /// and adds the script path to the config
    pub fn install_target_script(alias: &str, config: &mut config::Config) -> Result<(), Box<dyn error::Error>> {
        let install_dir = app_home_dir()?;
        let script_path = install_dir.join(alias);

        // Write script (overwrite if exists)
        fs::write(&script_path, format!(
            "#!/bin/bash\n# Script generated by binx\nexec {} {} \"$@\"",
            app_full_path()?.display(),
            alias
        ))?;

        // Set executable permissions
        let mut perms = fs::metadata(&script_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&script_path, perms)?;

        // Update existing alias with script path
        let script_path_str = script_path.to_string_lossy().to_string();

        config.aliases.get_mut(alias).unwrap().script = Some(script_path_str);
        
        println!("Successfully installed script");
        println!("You can next time run: {} [args]", alias);
    
        Ok(())
    }

    /// Gets the current executable path
    pub fn get_current_executable_path() -> Result<PathBuf, io::Error> {
        env::current_exe().map_err(|e| io::Error::new(io::ErrorKind::NotFound, e))
    }

    /// Gets the version of the installed executable by running it with --version
    fn get_installed_version() -> Option<String> {
        use std::process::Command;
        let output = Command::new(app_full_path().ok()?)
            .arg("--version")
            .output()
            .ok()?;
        
        if output.status.success() {
            let version_output = String::from_utf8_lossy(&output.stdout);
            // Parse version from output like "binx v0.1.0 or binx v0.1.0-1234567890"
            version_output
                .trim()
                .strip_prefix("binx v")
                .map(|v| v.to_string())
        } else {
            None
        }
    }

    /// Checks if the installed version is outdated compared to the current version
    pub fn is_version_outdated(current_version: &str) -> bool {
        if let Some(installed_version) = get_installed_version() {
            // Extract static version parts (before dash) for comparison
            let current_static = current_version.split('-').next().unwrap_or(current_version);
            let installed_static = installed_version.split('-').next().unwrap_or(&installed_version);
            
            // If current has static part but installed doesn't (or vice versa), it's outdated
            let current_has_static = current_static != current_version;
            let installed_has_static = installed_static != &installed_version;
            
            if current_has_static != installed_has_static {
                // Different build types (debug vs release), need update
                true
            } else if current_has_static {
                // Both have static parts, compare them
                installed_static != current_static
            } else {
                // Both are timestamps only (debug mode), compare full versions
                installed_version != current_version
            }
        } else {
            // If we can't get the version, assume it needs update
            true
        }
    }

    /// Performs the installation by moving the executable to ~/.binx/binx
    pub fn perform_installation() -> Result<(), io::Error> {
        let install_path = app_full_path()?;
        let current_path = get_current_executable_path()?;

        // Copy the current executable to the installation path
        fs::copy(&current_path, &install_path)?;

        // Set executable permissions
        let mut perms = fs::metadata(&install_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&install_path, perms)?;

        println!("{:?} ✔", install_path);

        Ok(())
    }

    /// Adds the installation directory to PATH in the shell's rc file
    pub fn add_to_path() -> Result<(), io::Error> {
        let install_dir = app_full_path()?;
        let install_dir_str = install_dir.to_string_lossy().to_string();
        let rc_path = system::detect_shell_rc().ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::NotFound,
                "Could not detect shell rc file",
            )
        })?;

        // Check if PATH already contains the installation directory
        if let Ok(path) = env::var("PATH") {
            if path.split(':').any(|p| p == install_dir_str) {
                println!("PATH ✔");
                return Ok(());
            }
        }

        // Read the rc file content
        let content = fs::read_to_string(&rc_path).unwrap_or_default();

        // Check if the PATH modification already exists in the rc file
        let path_line = format!("export PATH=\"$PATH:{}\"", install_dir_str);
        if content.contains(&install_dir_str) {
            return Ok(());
        }

        // Append the PATH modification to the rc file
        let new_content = if content.is_empty() {
            format!("{}\n", path_line)
        } else {
            format!("{}\n{}\n", content, path_line)
        };

        fs::write(&rc_path, new_content)?;
        println!("Added {:?} to PATH in {:?}", install_dir, rc_path);
        println!("Please run: source {:?}", rc_path);

        Ok(())
    }

    /// Runs the auto-installation check and performs installation if needed
    pub fn run_auto_installation(current_version: &str) -> Result<(), io::Error> {
        // If running from installation, do nothing        
        if get_current_executable_path()? == app_full_path()? {
            return Ok(());
        }

        // If installation exists, check if version is outdated
        let app_path = app_full_path()?;
        if app_path.exists() && app_path.is_file() {
            if is_version_outdated(current_version) {
                println!("Installed version is outdated, updating...");
                perform_installation()?;
                add_to_path()?;
            }
            return Ok(());
        }

        // Installation doesn't exist, perform installation
        println!("Performing auto-installation...");
        perform_installation()?;
        add_to_path()?;

        Ok(())
    }

    /// Finds an icon file (.png or .svg) with the same name as target in the target's directory
    pub fn find_icon_file(target_path: &PathBuf) -> Option<PathBuf> {
        let base_name = target_path.file_stem()?.to_str()?;
        let target_dir = target_path.parent()?;

        let svg_path = target_dir.join(format!("{}.svg", base_name));
        if svg_path.exists() {
            return Some(svg_path);
        }
        
        let png_path = target_dir.join(format!("{}.png", base_name));
        if png_path.exists() {
            return Some(png_path);
        }

        None
    }

    /// Installs an icon into the user icon theme and returns the icon name for the .desktop file
    pub fn install_icon_file(
        target: &str,
        icon_path: &PathBuf,
    ) -> Result<String, Box<dyn error::Error>> {
        let home_dir = system::get_home_dir()?;
        let icons_base = PathBuf::from(&home_dir).join(".local/share/icons/hicolor");

        let extension = icon_path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("png");

        let dest_dir = if extension == "svg" {
            icons_base.join("scalable/apps")
        } else {
            icons_base.join("256x256/apps")
        };

        fs::create_dir_all(&dest_dir)?;
        let dest_path = dest_dir.join(format!("{}.{}", target, extension));
        fs::copy(icon_path, &dest_path)?;

        match process::Command::new("gtk-update-icon-cache")
            .args(["-f", "-t"])
            .arg(&icons_base)
            .output()
        {
            Ok(output) if output.status.success() => {
                println!("Icon cache updated");
            }
            Ok(output) => {
                eprintln!(
                    "Warning: Icon cache update failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                );
            }
            Err(e) => {
                eprintln!("Warning: Could not run gtk-update-icon-cache: {}", e);
            }
        }

        Ok(target.to_string())
    }

    /// Generates the .desktop file content
    pub fn generate_desktop_content(
        alias: &str,
        exec_path: &str,
        try_exec_path: &str,
        icon_name: &str,
    ) -> String {
        // Capitalize first letter for Name
        let display_name = alias
            .chars()
            .enumerate()
            .map(|(i, c)| {
                if i == 0 {
                    c.to_uppercase().collect::<String>()
                } else {
                    c.to_string()
                }
            })
            .collect::<String>();

        format!(
            "[Desktop Entry]\n\
Type=Application\n\
Name={}\n\
Comment=Launch {} via binx\n\
Exec={}\n\
TryExec={}\n\
Icon={}\n\
Terminal=true\n\
NoDisplay=false\n\
Categories=Utility;\n",
            display_name, alias, exec_path, try_exec_path, icon_name
        )
    }

    /// Installs a .desktop file for the target in the applications directory
    pub fn install_desktop_file(
        alias: &str,
        target_path: &PathBuf,
        config: &mut config::Config,
    ) -> Result<(), Box<dyn error::Error>> {
        let apps_dir = system::get_user_applications_dir()?;
        let desktop_name = desktop_filename(alias);
        let desktop_file_path = apps_dir.join(format!("{}.desktop", desktop_name));

        let try_exec_path = app_full_path()?.to_string_lossy().to_string();
        let exec_path = format!("{} {}", try_exec_path, alias);

        // Install icon into the user icon theme when available
        let icon_name = if let Some(icon_path) = find_icon_file(target_path) {
            install_icon_file(alias, &icon_path)?
        } else {
            "application-x-executable".to_string()
        };

        let desktop_content =
            generate_desktop_content(alias, &exec_path, &try_exec_path, &icon_name);

        fs::write(&desktop_file_path, &desktop_content)?;
        let mut perms = fs::metadata(&desktop_file_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&desktop_file_path, perms)?;
        println!("Installed .desktop file: {:?}", desktop_file_path);

        // Validate the installed desktop file
        match process::Command::new("desktop-file-validate")
            .arg(&desktop_file_path)
            .output()
        {
            Ok(output) if !output.status.success() => {
                eprintln!(
                    "Warning: Desktop file validation failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                );
            }
            _ => {}
        }

        let desktop_file_path_str = desktop_file_path.to_string_lossy().to_string();

        if let Some(alias) = config.aliases.get_mut(alias) {
            alias.desktop = Some(desktop_file_path_str);
        }

        // Update desktop database so launchers pick up the new entry
        println!("Updating desktop database...");
        match process::Command::new("update-desktop-database")
            .arg(&apps_dir)
            .output()
        {
            Ok(output) if output.status.success() => {
                println!("Desktop database updated successfully");
            }
            Ok(output) => {
                eprintln!(
                    "Warning: Desktop database update failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                );
            }
            Err(e) => {
                eprintln!("Warning: Could not run update-desktop-database: {}", e);
            }
        }

        Ok(())
    }
}

/// Configuration management
pub mod config {
    use serde::{Deserialize, Serialize};
    use std::collections::HashMap;
    use std::fs;
    use std::io;

    pub use crate::utils::system;

    #[derive(Serialize, Deserialize)]
    pub struct ConfigAlias {
        pub path: String,
        pub script: Option<String>,
        pub desktop: Option<String>,
        pub icon: Option<String>,
    }

    #[derive(Serialize, Deserialize)]
    pub struct Config {
        pub aliases: HashMap<String, ConfigAlias>,
    }

    pub const CONFIG_VERSION: &str = "1.0.0";
    const CONFIG_FILE: &str = ".config/binx.json";
    const DEFAULT_CONFIG: &str = r#"{
      "aliases": {}
    }"#;

    /// Gets the configuration file path
    pub fn get_config_file_path() -> Result<String, io::Error> {
        let home_dir = system::get_home_dir()?;
        Ok(format!("{}/{}", home_dir, CONFIG_FILE))
    }

    pub fn save_config(config: &Config) -> Result<(), io::Error> {
        let config_path = get_config_file_path()?;
        let config_str = serde_json::to_string_pretty(config)?;
        fs::write(&config_path, config_str)?;
        Ok(())
    }

    pub fn load() -> Result<Config, io::Error> {
        let config_path = get_config_file_path()?;

        let content = match fs::read_to_string(&config_path) {
            Ok(content) => {
                if content.trim().is_empty() {
                    fs::write(&config_path, DEFAULT_CONFIG)?;
                    DEFAULT_CONFIG.to_string()
                } else {
                    content
                }
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => {
                fs::write(&config_path, DEFAULT_CONFIG)?;
                DEFAULT_CONFIG.to_string()
            }
            Err(e) => return Err(e.into()),
        };

        let config: Config = serde_json::from_str(&content)?;
    
        Ok(config)
    }
}

/// Flow management
pub mod flow {
    use nix::unistd::execve;
    use std::env;
    use std::ffi::CString;

    #[allow(unreachable_code)]
    pub fn execute(bin_path: &str, bin_args: &[String]) {
        let path = CString::new(bin_path).expect("Failed to create CString");

        let mut c_args: Vec<CString> = Vec::with_capacity(bin_args.len() + 1);
        c_args.push(path.clone());
        for arg in bin_args {
            c_args.push(CString::new(arg.as_str()).expect("Failed to create CString"));
        }

        let c_args_refs: Vec<&CString> = c_args.iter().collect();

        let c_env: Vec<CString> = env::vars()
            .map(|(k, v)| CString::new(format!("{}={}", k, v)).expect("Failed to create CString"))
            .collect();
        let c_env_refs: Vec<&CString> = c_env.iter().collect();

        execve::<&CString, &CString>(&path, &c_args_refs, &c_env_refs).expect("Failed to exec");
    }
}
